name: setup-generic-tool
description: Setup arbitrary tools from GitHub Releases or tool cache
author: isometry
inputs:
  name:
    description: GitHub repository of the desired tool
    required: true
  tool:
    description: Override tool name, if it doesn't match the repo name
    required: false
    default: ""
  version:
    description: Version of tool to install
    required: false
    default: latest
outputs:
  version:
    description: Version of tool installed
runs:
  using: node20
  main: dist/index.js
