name: setup-generic-tool
description: Setup arbitrary tools from GitHub Releases or tool cache
author: isometry

inputs:
  name:
    description: GitHub repository of the desired tool
    required: true
  tool:
    description: Override tool name, if it doesn't match the repo name
    required: false
    default: ""
  asset:
    description: Override asset name, if it doesn't match the tool name
    required: false
    default: ""
  version:
    description: Version of tool to install
    required: false
    default: latest

outputs:
  version:
    description: Version of tool installed
    value: ${{ steps.setup.outputs.version }}

runs:
  using: composite
  steps:
    - name: Setup Tool
      id: setup
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
        TOOL: ${{ inputs.tool }}
        ASSET: ${{ inputs.asset }}
      run: |
        "${GITHUB_ACTION_PATH}/setup.sh" "${NAME}" "${VERSION}" "${TOOL}" "${ASSET}"
