name: Test action

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v4

      - run: apt update && apt install -y curl jq unzip

      - uses: ./
        with:
          name: cli/cli
          tool: gh
      - run: gh --version

      - uses: ./
        with:
          name: aquasecurity/trivy
      - run: trivy --version

      - uses: ./
        with:
          name: mikefarah/yq
      - run: yq --version

      - uses: ./
        with:
          name: chainguard-dev/apko
          version: v0.19.0
      - run: apko version

      - uses: ./
        with:
          name: nexthink-oss/ghup
          version: v0.12.0
      - run: ghup --version

      - uses: ./
        with:
          name: gruntwork-io/terragrunt
          version: v0.67.16
      - run: terragrunt --version

      - uses: ./
        with:
          name: yannh/kubeconform
      - run: kubeconform -v
